[package]
name = "pwmixer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
crossterm = "0.28.1"
libspa = "0.8.0"
libspa-sys = "0.8.0"
log = "0.4.24"
pipewire = { version = "0.8.0", features = ["v0_3_44"] }
ratatui = "0.29.0"
