[package]
name = "pwmixer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.26", features = ["derive"] }
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
futures-timer = "3.0.3"
libspa = "0.8.0"
libspa-sys = "0.8.0"
log = "0.4.24"
nix = { version = "0.29.0", features = ["event"] }
pipewire = { version = "0.8.0", features = ["v0_3_44"] }
ratatui = "0.29.0"
scopeguard = "1.2.0"
