name: ci
on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: ./.github/actions/setup-dependencies
      - name: Build wiremix
        run: cargo build --locked --all-features --all-targets
      - name: Run tests
        run: cargo test --locked --all-features --all-targets
      - name: Run doc tests
        run: cargo test --locked --all-features --doc
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
      - name: Check Nix formatting
        run: |
          nix shell nixpkgs#nixfmt-rfc-style -c \
            find . -name '*.nix' -exec nixfmt -sw 80 --check {} +
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check Rust formatting
        run: cargo fmt --all --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: ./.github/actions/setup-dependencies
      - name: Run clippy
        run: cargo clippy --locked --all-features --all-targets -- -D warnings
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: ./.github/actions/setup-dependencies
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --locked --no-deps --document-private-items
